### ISSUE TITLE
Adding entry doesn't work on Firefox 64 / MacOS

### ISSUE THREAD

**Issue by tiberiuana** [trys/JournalBook#27]
Hi, nice project 🥇! 
I think I found a problem on Firefox:

To reproduce: 

* https://journalbook.co.uk/get-started on a new computer (or private window)
* Click one of the preset questions

Expected: 

* question gets selected

Actual:
* nothing happens.

Error in the console: 

```
InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.
TypeError: n.state.db is null[Learn More]
```

**Comment by trys** [comment]
Oh no! Good spot, I'll check that out asap!

**Comment by trys** [comment]
This seems really temperamental to reproduce. I've cleared the site data, and manually deleted the DB, and it keeps rebuilding correctly. In Firefox private mode, IDB appears to be disabled (by design) so it's even more of a beast to debug. I'll keep digging! 😩

**Comment by tiberiuana** [comment]
I just tried it with Firefox 64 on another Mac and it worked. It could be that I was in a private window at work and, as you say, IDB just won't work there, I'll double check tomorrow. 

If that is the case, the simple solution is to have the app complain, instead of database access failing quietly.

**Comment by jschopplich** [comment]
I trust tried again on the same setup (macOS, Firefox 64) and had no problems inside a normal browser window.

Opening the journal in a private session immediately throws: `InvalidStateError: A mutation operation was attempted on a database that did not allow mutations.`
Adding a custom question or entering text in the following steps later throws `TypeError: n.state.db is null[Weitere Informationen]`

Using the journal inside a private window is anything but the use case – particularly because everything written is thrown away anyway – so I guess this is issue is not important to fix?

**Comment by trys** [comment]
Better error handling would be a good move regardless of the private browsing problem, even if there's just a message saying something like `There was a setting up the local data store [try again]`.

It just seems bizarre that a totally fresh FF load seems to trigger the problem too, but I can't for the life of me get it to happen again!
